import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        zIndex:-1,
        position: 'fixed',
        width : '100vw',
        height : '100vh'
      }}>
        <Image
          src="/bg.jpg"
          alt="background image"
          layout='fill'
          objectFit='cover'
        />
      </div>
      <div style={{
        position : 'absolute',
        top : '50%',
        left : '50%',
        transform : 'translate(-50,-50)',
        
      }}>

      
        <button className="bg-indigo-300 hover:bg-indigo-900 text-white font-bold py-2 px-4 rounded-md" onClick={() => {
          router.push('./login')
        }}>Click Here to Start !</button>
      </div>
    </>
  )
}
